"""
GitHub operations using a hybrid approach:
- PyGithub  → file fetch, branch ref creation, PR creation
- GitPython → local clone, file mutation, commit, push

This hybrid avoids the GitHub API's complex multi-file commit requirement
while still using the cleaner API surface for branch/PR management.
"""
import os
import shutil
from typing import Optional

from github import Github, GithubException
from git import Repo

from app.config import settings
from app.logger import get_logger

log = get_logger(__name__)


# ---------------------------------------------------------------------------
# Client helpers
# ---------------------------------------------------------------------------

def _get_github_repo():
    g = Github(settings.github_pat)
    return g.get_repo(f"{settings.github_repo_owner}/{settings.github_repo_name}")


# ---------------------------------------------------------------------------
# File fetching (pre-clone, used during classification)
# ---------------------------------------------------------------------------

def fetch_java_file(file_path: str) -> str:
    """
    Fetch raw Java source from GitHub via API.
    file_path must be the full repo-relative path, e.g.
    'src/test/java/com/example/OrderApiTest.java'
    """
    repo = _get_github_repo()
    try:
        content = repo.get_contents(file_path, ref=settings.github_default_branch)
        return content.decoded_content.decode("utf-8")
    except GithubException as e:
        raise FileNotFoundError(
            f"Could not fetch '{file_path}' from GitHub "
            f"({settings.github_repo_owner}/{settings.github_repo_name}): {e}"
        )


def resolve_file_path(class_path: str) -> str:
    """
    Resolve a class path like 'com/example/OrderApiTest.java' to the full
    repo-relative path by searching the repository tree.

    Returns the first match. If multiple matches exist a warning is printed
    and the first result is used (deterministic; adjust if needed).
    """
    # If class_path already looks like a full path, try it directly first
    if class_path.startswith("src/"):
        try:
            fetch_java_file(class_path)
            return class_path
        except FileNotFoundError:
            pass

    java_file = class_path.split("/")[-1]  # e.g. "OrderApiTest.java"

    if not java_file or java_file == ".java":
        raise FileNotFoundError(
            f"Cannot resolve file path: class_path is empty or invalid ('{class_path}'). "
            "The parser did not extract a class name for this test failure."
        )

    repo = _get_github_repo()
    tree = repo.get_git_tree(settings.github_default_branch, recursive=True)

    matches = [item.path for item in tree.tree if item.path.endswith(java_file)]

    if not matches:
        raise FileNotFoundError(
            f"No file matching '{java_file}' found in "
            f"{settings.github_repo_owner}/{settings.github_repo_name}"
        )

    if len(matches) > 1:
        log.warning("Multiple file matches, using first result", extra={"java_file": java_file, "matches": matches})

    return matches[0]


# ---------------------------------------------------------------------------
# Branch name helper
# ---------------------------------------------------------------------------

def create_fix_branch_name(job_id: str) -> str:
    return f"test-fix-job-{job_id}"


# ---------------------------------------------------------------------------
# Local repo operations (GitPython)
# ---------------------------------------------------------------------------

def clone_repository(local_path: str) -> Repo:
    """Clone repo using PAT-authenticated HTTPS URL."""
    auth_url = (
        f"https://{settings.github_pat}@github.com/"
        f"{settings.github_repo_owner}/{settings.github_repo_name}.git"
    )
    if os.path.exists(local_path):
        shutil.rmtree(local_path)
    return Repo.clone_from(auth_url, local_path, branch=settings.github_default_branch)


def write_fixed_file(local_repo_path: str, file_path: str, new_content: str) -> None:
    """Write fixed Java content to the local working tree."""
    full_path = os.path.join(local_repo_path, file_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(new_content)


def commit_and_push_fixes(
    local_repo: Repo,
    branch_name: str,
    changed_files: list[str],
    job_id: str,
) -> None:
    """Create a local branch, stage changed files, commit, and push."""
    local_repo.git.checkout("-b", branch_name)
    local_repo.index.add(changed_files)
    local_repo.index.commit(
        f"fix(tests): automated assertion fixes for job {job_id}\n\n"
        f"Generated by Agentic Test Suite Maintenance System.\n"
        f"Files modified: {', '.join(changed_files)}"
    )
    origin = local_repo.remote("origin")
    origin.push(refspec=f"{branch_name}:{branch_name}")


# ---------------------------------------------------------------------------
# Remote branch creation (PyGithub)
# ---------------------------------------------------------------------------

def create_remote_branch(branch_name: str) -> None:
    """Create the branch ref on the remote before pushing."""
    repo = _get_github_repo()
    source_branch = repo.get_branch(settings.github_default_branch)
    source_sha = source_branch.commit.sha
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=source_sha)
        log.info("Remote branch created", extra={"branch": branch_name})
    except GithubException as e:
        if e.status == 422:
            log.warning("Branch already exists, continuing", extra={"branch": branch_name})
        else:
            raise


# ---------------------------------------------------------------------------
# PR creation (PyGithub)
# ---------------------------------------------------------------------------

def generate_pr_body(job_id: str, fixed_failures: list[dict]) -> str:
    lines = [
        f"## Automated Test Fixes — Job `{job_id}`",
        "",
        "This PR was generated by the **Agentic Test Suite Maintenance System**.",
        "All changes have been reviewed and approved by a QA engineer.",
        "",
        "### Changes Made",
        "",
        "| Test Name | File | Change Summary |",
        "|-----------|------|----------------|",
    ]
    for f in fixed_failures:
        lines.append(
            f"| `{f['test_name']}` "
            f"| `{f['test_class_path']}` "
            f"| {f.get('changes_description', 'Assertion updated')} |"
        )
    lines += [
        "",
        "### Guardrail Classification",
        "All modified tests were classified as `SAFE_TO_FIX` by the LLM classifier,",
        "meaning they are negative/error scenarios where only the expected error value changed.",
        "",
        "> ⚠️ Tests classified as `BACKEND_BUG` were excluded and require manual investigation.",
    ]
    return "\n".join(lines)


def create_pull_request(job_id: str, branch_name: str, pr_body: str) -> str:
    """Create a PR via PyGithub and return the PR HTML URL."""
    repo = _get_github_repo()
    pr = repo.create_pull(
        title=f"Automated Test Fixes for Job {job_id}",
        body=pr_body,
        head=branch_name,
        base=settings.github_default_branch,
    )
    try:
        pr.add_to_labels("automated", "test-fix")
    except GithubException:
        log.warning("Could not add labels to PR (labels may not exist in repo)", extra={"pr_url": pr.html_url})
    log.info("Pull request created", extra={"pr_url": pr.html_url, "job_id": job_id})
    return pr.html_url
